directories:
  output: release
  buildResources: build
appId: com.nexus.desktop
productName: Project Nexus
electronVersion: 28.1.0
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
files:
  - filter:
      - dist/**/*
      - package.json
